### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by netypoj** [MeckeDev/cs2-inspect-gui#1]
I ran the pre_start file, everything was fine, everything downloaded, but after running the start file, an error was thrown "This application failed to start because nno Qt platform plugin could be initialized. Reinstalling the application may fix this problem". 
It seems to me that you did not add all the necessary libraries in the pre_start file and this is precisely why the error appears

**Comment by MeckeDev** [comment]
Thanks for reporting your Problem, i am currently trying to transform this Python Tool into a Website, but i have to wait for my Friend who has better skills at UI than me, the Python Tool might get abandoned soon.

**Comment by 21ALRAM21** [comment]
unfortunately, I have the same problem as C3mka21, nothing works.

**Comment by MeckeDev** [comment]
I can recommend using the Website instead, its still very early and i want to switch from PHP to Javascript soon, but atleast it should work:
https://www.meckedev.de

**Comment by 21ALRAM21** [comment]
Why the program? if there is your brilliant website? Friend, tell me how you can see the skins right in the game itself, so that you can twist the weapon, if you tell me, I'll tell you!

**Comment by MeckeDev** [comment]
if you have the Game opened it should show the Skin after clicking on "Open Preview" if this does not work you can click on "Copy Command" and put that command in CS2 into the Console

**Comment by 21ALRAM21** [comment]
No, friend, you didn't understand, not just an inspection with the mouse, namely, to run with a skin on the map, perhaps there is some code that will change the skin right in the game, but just on the training server.

**Comment by MeckeDev** [comment]
In CS2 it is not possible to take the Skins in your Hand, if you are in CSGO there are a couple Servers like from Ohnepixel where you could check the Skins in the Game directly, but my generated Links sometimes do not Work on these Servers, i will add the "!gen" Codes for these Servers soon on the Website

**Comment by 21ALRAM21** [comment]
But how did he do it? he has a bunch of videos from cs2 where he reviews skins with stickers right on the map.
https://www.youtube.com/watch?v=0LPRh3x4ILI
Name channel: roboguerreiroCSGO

**Comment by MeckeDev** [comment]
I don't know how he is doing it, but maybe you could ask him. Maybe he owns the Skins, maybe he is using Hacks like a Skinchanger

**Comment by 21ALRAM21** [comment]
Oh yeah.... how did I not think of it right away... He does not respond to any message, as if he has a skinchanger! That's why he didn't tell anyone about it.

**Comment by MeckeDev** [comment]
i added the "!gen" Commands to the Website, so you can inspect it on CSGO Skin Servers atleast, but in CS2 the only way would be a Skinchanger as far as i know. But i am not a Hack/Cheat Developer. And i own the biggest VAC Database for a Reason :) 

https://www.meckedev.de/vac

**Comment by 21ALRAM21** [comment]
Buddy, you're very good! But yes, I'm sure now that he works with a skinchanger, I won't do that, I'm afraid I'll get banned...

**Comment by 21ALRAM21** [comment]
Friend, can you tell me when to expect a correction according to your program? still, I think it will be more convenient to work with the program.

**Comment by MeckeDev** [comment]
I will not work on the Tool for a while, i will focus on the Website for now

i added a Feature to keep the Values from your last Craft and i made the UI a bit better

**Comment by 21ALRAM21** [comment]
Oh, and really you edited the site so quickly! Then now there really is no need for a program. Thank you friend, how can I support you?

**Comment by MeckeDev** [comment]
Just use the Page and share it, let me know if something does not work.

i will add tons of Stuff to the Page, it is still missing a lot of Stickers and stuff like that.
i will also rename some of the Skins, since the Skins sometimes do not fit the Weapon, if you pick Asiimov on an AK it's the AWP Asiimov on an AK for example.

**Comment by MeckeDev** [comment]
We now have Servers where you can use the !gen Codes to inspect Weapons ingame:

Enjoy:

connect inspect.epidemic.gg
connect inferno.epidemic.gg
connect vertigo.epidemic.gg
connect dust2.epidemic.gg
connect ancient.epidemic.gg
connect nuke.epidemic.gg

Everything should work, excepts Gloves atm

**Comment by 21ALRAM21** [comment]
Do you still not know how to view weapons directly on the server?

**Comment by MeckeDev** [comment]
This Tool is no longer updated and supported, the Tool got replaced with a very nice Website, use the Website and visit my Steam if you have any Questions <3 

Website: https://www.meckedev.de
Steam: https://steamcommunity.com/id/mecke_dev/
